### ISSUE TITLE
ntJoin error: Sorted input specified, but the file has the following record with a different sort order than the genomeFile 

### ISSUE THREAD

**Issue by musaqa** [bcgsc/ntJoin#97] opened 2023-09-07 16:01 UTC
As you suggested I tried improving my chosen assembly using assemblies generated with other k-mer sizes with your ntJoin tool, but I am experiencing an error. The input files are abyss assemblies without any postprocessing after the assembly (eg. filename_abyss_k105-8.fa). I tried a few assemblies as a target and as a reference, but the error persists. The fasta files are single-lined as they should be, I tried both with soft-links and the "real" files in the directory but the error is still there. Also your test_installation.sh script works. Bedtools version is bedtools v2.31.0, so it should be the latest version. These are some of the commands that I tried:

ntJoin assemble target=ACH01_abyss_k105-8.fa target_weight=1 references='ACH01_abyss_k159-8.fa' reference_weights='1' t=63 k=32 w=500

ntJoin assemble target=ACH01_abyss_k105-8_s.fa target_weight=1 reference_config=config_multiple1.csv prefix=f-1_k101 t=63 k=101 w=1000 

And this is the error that I get:

2023-09-07 10:28:45.515713 : Printing output scaffolds
Traceback (most recent call last):
  File "/home/peric/anaconda3/envs/mamba/envs/ntjoin_new/bin/share/ntjoin-1.1.1-2/bin/ntjoin_assemble.py", line 1115, in <module>
    main()
  File "/home/peric/anaconda3/envs/mamba/envs/ntjoin_new/bin/share/ntjoin-1.1.1-2/bin/ntjoin_assemble.py", line 1112, in main
    Ntjoin().main()
  File "/home/peric/anaconda3/envs/mamba/envs/ntjoin_new/bin/share/ntjoin-1.1.1-2/bin/ntjoin_assemble.py", line 1102, in main
    self.print_scaffolds(paths, intersecting_regions)
  File "/home/peric/anaconda3/envs/mamba/envs/ntjoin_new/bin/share/ntjoin-1.1.1-2/bin/ntjoin_assemble.py", line 873, in print_scaffolds
    outfile = self.print_unassigned(assembly, assembly_fa, incorporated_segments, outfile, params)
  File "/home/peric/anaconda3/envs/mamba/envs/ntjoin_new/bin/share/ntjoin-1.1.1-2/bin/ntjoin_assemble.py", line 890, in print_unassigned
    missing_bed = genome_bed.complement(i=incorporated_segments_bed, g=genome_dict)
  File "/home/peric/anaconda3/envs/mamba/envs/ntjoin_new/lib/python3.10/site-packages/pybedtools/bedtool.py", line 909, in decorated
    result = method(self, *args, **kwargs)
  File "/home/peric/anaconda3/envs/mamba/envs/ntjoin_new/lib/python3.10/site-packages/pybedtools/bedtool.py", line 388, in wrapped
    stream = call_bedtools(
  File "/home/peric/anaconda3/envs/mamba/envs/ntjoin_new/lib/python3.10/site-packages/pybedtools/helpers.py", line 460, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools complement -i /tmp/pybedtools._df0h1ef.tmp -g /tmp/pybedtools.8thg8ecw.tmp

Error message was:
Error: Sorted input specified, but the file /tmp/pybedtools._df0h1ef.tmp has the following record with a different sort order than the genomeFile /tmp/pybedtools.8thg8ecw.tmp
10408   0       22111

make: *** [/home/peric/anaconda3/envs/mamba/envs/ntjoin_new/bin/share/ntjoin-1.1.1-2/ntJoin:227: ACH01_abyss_k105-8_s.fa.k101.w1000.n1.assigned.scaffolds.fa] Error 1
make: *** Deleting file 'ACH01_abyss_k105-8_s.fa.k101.w1000.n1.assigned.scaffolds.fa'

Best Regards,
Pavle

**Comment by lcoombe** [comment] 2023-09-07 16:04
Thanks for moving this issue here, Pavle!

I'll look into it - in the meantime, could you also provide the full log of the failed ntJoin test, and result of `conda list`? I just want to double check that everything prior to this step in the ntJoin run looks OK.

Thanks!
Lauren

**Comment by lcoombe** [comment] 2023-09-07 16:34
Hi Pavle,

Is your pybedtools version 0.9.1? On my end, I just did a test with pybedtools 0.9.0, then 0.9.1, and I was able to reproduce your failure with v0.9.1 only. 

So while I'm looking into the error more, a quick fix could be to try downgrading pybedtools to 0.9.0. Looks like v0.9.1 was only released around a 1 month ago, which could be why we haven't come across this yet.

**Comment by musaqa** [comment] 2023-09-07 16:43
[mamba list.txt](https://github.com/bcgsc/ntJoin/files/12551558/mamba.list.txt)
Here is the output of mamba list, yes the pybedtools version is 0.9.1 so i will try with the older version. I dont have the full log file, but i will run it again and save the log, to send you if it fails again.

Best regards,
Pavle

**Comment by lcoombe** [comment] 2023-09-07 16:45
Sounds good, thanks! 
Yes, let me know if the downgrade fixes it - if so, I'll temporarily pin the version of pybedtools to <0.9.1 in the conda recipe until I have a better fix.
Thanks for reporting this issue!

**Comment by lcoombe** [comment] 2023-09-07 18:09
FYI - I also drafted a fix in https://github.com/bcgsc/ntJoin/pull/98

**Comment by musaqa** [comment] 2023-09-07 19:03
Thank you Lauren, downgrading the pybedtools to 0.9.0 worked. I have a question for you. Is it better to put a few assemblies as references at once and give them all the same weight or should I try to improve the target with only one assembly (second best or the one with the most different busco genes missing lets say), and than try to improve the output of that one with another, and so on? and should references have higher weight than the target (if I am using other k-mer assemblies).

Thanks in advance,
Pavle

**Comment by lcoombe** [comment] 2023-09-07 19:11
Hi Pavle,

Great, thanks for letting me know! I'll merge the PR today and make a new release so that this shouldn't be an issue in the future.

Good question - I have tried in both ways with draft ABySS assemblies. In my tests, running iteratively (ie. improving with one assembly, then taking that output and improving with the next assembly, etc) yielded slightly better results as compared to supplying many references at once. 

Yes, I do recommend setting the reference(s) to have higher weight than the target, but for your case I'd keep the edge weight threshold `n` at the default (`n=1`)

**Comment by lcoombe** [comment] 2023-09-29 21:50
The fixed code is in the ntJoin v1.1.3 release - thanks again!
Feel free to open a new issue if you have any further questions.

**Closed by lcoombe** 2023-09-29 21:50 UTC
